#!/bin/bash

## Copyright (C) 2021 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#set -x
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose
export LC_ALL=C

## security-misc-shared Depends on helper-scripts.
# shellcheck source=../../../../../helper-scripts/usr/libexec/helper-scripts/has.sh
source "${HELPER_SCRIPTS_PATH:-}"/usr/libexec/helper-scripts/has.sh

## Check if the VirtualBox host software is installed.
if ! has vboxmanage ; then
   ## VirtualBox host software is not installed.
   if test -f /etc/sysctl.d/30-lkrg-virtualbox.conf ; then
      ## Delete using '--verbose' so user is notified.
      safe-rm --force --verbose -- /etc/sysctl.d/30-lkrg-virtualbox.conf
   fi
   exit 0
fi

if ! test -d /etc/sysctl.d ; then
   exit 0
fi

if ! test -f /usr/share/security-misc/lkrg/30-lkrg-virtualbox.conf ; then
   exit 0
fi

if ! package-installed-check "lkrg" ; then
   exit 0
fi

## Delete using '--verbose' so user is notified.
cp --verbose -- /usr/share/security-misc/lkrg/30-lkrg-virtualbox.conf /etc/sysctl.d/30-lkrg-virtualbox.conf
