.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "APPARMOR\-WATCH" "8" "January 2020" "security-misc" "security-misc Manual"
.SH "NAME"
\fBapparmor\-watch\fR \- Watch AppArmor DENIED and ALLOWED Log Messages
.SH "SYNOPSIS"
\fBapparmor\-watch\fR
.SH "DESCRIPTION"
Watches for AppArmor \fBDENIED\fR and \fBALLOWED\fR log messages\.
.SH "EXAMPLE"
\fBsudo apparmor\-watch\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
