#!/bin/sh

## Copyright (C) 2019 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ -x /usr/lib/security-misc/panic-on-oops ]; then
   sudo --non-interactive /usr/lib/security-misc/panic-on-oops
fi
