#!/bin/sh

## Copyright (C) 2019 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

if [ -x /usr/lib/security-misc/panic-on-oops ]; then
   sudo --non-interactive /usr/lib/security-misc/panic-on-oops
fi
