#!/bin/bash

## Copyright (C) 2019 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

title="$0: password required for $(whoami) to perform action as superuser"

zenity --password --title="$title"
