#!/bin/bash

## Copyright (C) 2019 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## https://serverfault.com/questions/134471/success-n-control-syntax-in-pam-conf-pam-d-files

set -x

true "PAM_SERVICE: $PAM_SERVICE"

if [ "$PAM_SERVICE" = "login" ]; then
   ## FIXME:
   ## Creates unwanted journal log entry.
   ## pam_exec(login:account): /usr/lib/security-misc/pam_only_if_login failed: exit code 1
   exit 1
else
   ## exit success so [success=1 default=ignore] will result in skipping the
   ## next pam module.
   exit 0
fi
