#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

# Makes the kernel panic on oopses.
sysctl kernel.panic_on_oops=1
