#!/bin/bash

set -x

home_folder_access_rights_lockdown() {
   mkdir -p /var/cache/security-misc/state-files

   shopt -s nullglob

   ## Not using dotglob.
   ## touch /var/cache/security-misc/state-files//home/.Trash
   ## touch: cannot touch '/var/cache/security-misc/state-files//home/.Trash': No such file or directory

   local folder_name base_name

   for folder_name in /home/* ; do
      base_name="$(basename "$folder_name")"
      if [ -f "/var/cache/security-misc/state-files/$base_name" ]; then
         continue
      fi
      chmod o-rwx "$folder_name"
      ## Create a state-file so we do this only once.
      ## Therefore a user who will manually undo this, will not get
      ## annoyed by this being done over and over again.
      touch "/var/cache/security-misc/state-files/$base_name"
   done

   shopt -u nullglob
}

home_folder_access_rights_lockdown

exit 0
