#!/bin/bash

## Copyright (C) 2019 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if test -x /usr/lib/security-misc/remove-system.map ; then
   /usr/lib/security-misc/remove-system.map
fi
