#!/bin/bash

## Copyright (C) 2019 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

if test -x /usr/libexec/security-misc/remove-system.map ; then
   /usr/libexec/security-misc/remove-system.map
fi
