#!/bin/sh 

## Source debconf lib
. /usr/share/debconf/confmodule

db_set security-misc/add_user_to_sudo false
db_set security-misc/add_user_to_console false
db_input high security-misc/add_user_to_sudo
db_input high security-misc/add_user_to_console

db_go
