#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

if [ -f /usr/libexec/helper-scripts/pre.bsh ]; then
   source /usr/libexec/helper-scripts/pre.bsh
fi

set -e

true "
#####################################################################
## INFO: BEGIN: $DPKG_MAINTSCRIPT_PACKAGE $DPKG_MAINTSCRIPT_NAME $@
#####################################################################
"

if [ "$1" = remove ]; then
   ## REMINDER: This list of policies must be kept in sync with the contents of
   ## usr/share/pam-configs.
   pam-auth-update --package --remove \
      block-unsafe-logins-security-misc \
      console-lockdown-security-misc \
      faillock-preauth-security-misc \
      mkhomedir-security-misc \
      pam-abort-on-locked-password-security-misc \
      umask-security-misc \
      unix-faillock-security-misc \
      wheel-security-misc
fi

true "INFO: debhelper beginning here."

#DEBHELPER#

true "INFO: Done with debhelper."

true "
#####################################################################
## INFO: END  : $DPKG_MAINTSCRIPT_PACKAGE $DPKG_MAINTSCRIPT_NAME $@
#####################################################################
"

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
