#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

export LC_ALL=C

write_pid_file() {
  safe-rm -r -f -- "/run/helper-scripts/security-misc-apt-get-update-pid"
  install -m644 /dev/null "/run/helper-scripts/security-misc-apt-get-update-pid"
  echo "$$" | sponge -- "/run/helper-scripts/security-misc-apt-get-update-pid"
}

sigterm_trap() {
   if [ "$lastpid" = "" ]; then
      exit 143
   fi
   if kill -0 -- "$lastpid" &>/dev/null ; then
      kill -s sigterm -- "$lastpid"
   fi
   exit 143
}

trap "sigterm_trap" SIGTERM SIGINT

[[ -v timeout_after ]] || timeout_after="600"
[[ -v kill_after ]] || kill_after="10"

write_pid_file

timeout \
   --kill-after="$kill_after" \
   "$timeout_after" \
   apt-get update --error-on=any "$@" &

lastpid="$!"
wait "$lastpid"

exit "$?"
