#!/bin/bash

## Copyright (C) 2019 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

title="$0: password required for $(whoami) to perform action as superuser"

zenity --password --title="$title"
