#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

## security-misc-shared Depends on helper-scripts.
# shellcheck source=../../../../helper-scripts/usr/libexec/helper-scripts/has.sh
source /usr/libexec/helper-scripts/has.sh

export LC_ALL='C'

## Package 'pciutils' provides tool 'lspci'.
has lspci

if lspci | grep --quiet '^[^ ]* USB controller: '; then
  exit 0
fi

exit 1
