#!/bin/bash

## Copyright (C) 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## Copyright (C) 2023 - 2023 Friedrich Doku <friedrichdoku@gmail.com>
## See the file COPYING for copying conditions.

#set -x
set -e

## provided by helper-scripts
kernel=$(kernel-file-detect)
initrd=$(initrd-file-detect)

if   systemctl list-jobs --no-legend | grep "poweroff.target" | grep -q "start"; then
   wiperamexit="yes"
   wiperamaction="poweroff"
elif systemctl list-jobs --no-legend | grep "reboot.target" | grep -q "start"; then
   wiperamexit="yes"
   wiperamaction="reboot"
elif systemctl list-jobs --no-legend | grep "halt.target" | grep -q "start"; then
   wiperamexit="yes"
   wiperamaction="halt"
else
   ## Could be kexec.target.
   ## Could be run during package installation.
   echo "$0: INFO: Neither poweroff, reboot or halt. Therefore skipping 'kexec --load', ok."
   exit 0
fi

echo "INFO: wiperamaction: $wiperamaction"

## Debugging.
echo kexec --load "$kernel" --initrd="$initrd" --reuse-cmdline --append="wiperamexit=$wiperamexit wiperamaction=$wiperamaction"

kexec --load "$kernel" --initrd="$initrd" --reuse-cmdline --append="wiperamexit=$wiperamexit wiperamaction=$wiperamaction"

echo "OK."
