#!/bin/bash

## Copyright (C) 2023 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

sysctl -w kernel.modules_disabled=1

true "The loading of new modules to the kernel has been disabled by security-misc."
