#!/bin/bash

# Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
# See the file COPYING for copying conditions.

gcc \
  -o \
  /run/force-shutdown-when-device-removed \
  -static \
  /usr/src/security-misc/force-shutdown-when-device-removed.c \
  || {
    printf "%s\n" 'Could not compile force-shutdown executable!'
    exit 1;
  }

readarray -t root_devices < <(/usr/libexec/helper-scripts/get-backing-devices-for-mountpoint '/');

## memlockd daemonizes itself, so no need to background it
memlockd -c /usr/share/security-misc/security-misc-memlockd.cfg

/run/force-shutdown-when-device-removed "${root_devices}" &
sleep 1
disown
exit 0
