#!/bin/bash

## Copyright (C) 2019 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## https://serverfault.com/questions/134471/success-n-control-syntax-in-pam-conf-pam-d-files

set -x
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

true "PAM_SERVICE: ${PAM_SERVICE:-}"

if [ "${PAM_SERVICE:-}" = "login" ]; then
   ## exit 1 drives the [success=1 default=ignore] control flow (fall through
   ## to the next PAM module). It previously emitted a journal line
   ##   pam_exec(login:account): ... pam_only_if_login failed: exit code 1
   ## now suppressed by 'quiet_log' on the pam_exec.so line in
   ## /usr/share/pam-configs/console-lockdown-security-misc (linux-pam >= 1.5.2;
   ## plain 'quiet' only hides the user-facing message, not the log).
   exit 1
else
   ## exit success so [success=1 default=ignore] will result in skipping the
   ## next pam module.
   exit 0
fi
