#!/bin/sh

## Copyright (C) 2012 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

. /usr/share/initramfs-tools/hook-functions
copy_exec /sbin/sysctl /sbin
