#!/bin/sh

## Copyright (C) 2012 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}
case $1 in
prereqs)
       prereqs
       exit 0
       ;;
esac

. /usr/share/initramfs-tools/hook-functions
copy_exec /sbin/sysctl /sbin
